baseURL = "https://rustdesk.com/docs"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "RustDesk Documentation"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/rustdesk/doc.rustdesk.com/edit/master/content/"
  description = "Documentation for RustDesk"
  author = "RustDesk"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"
  themeVariant = "blue"
  custom_css = ["css/theme-mine.css"]

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for RustDesk"
weight = 1
languageName = "English"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/rustdesk/rustdesk"
weight = 10

[Languages.fr]
title = "Documentation du RustDesk"
weight = 2
languageName = "Français"
landingPageName = "<i class='fas fa-home'></i> Page d'accueil"

[Languages.ru]
title = "Документация для RustDesk"
weight = 2
languageName = "Русский"
landingPageName = "<i class='fas fa-home'></i> Домашняя страница"

[Languages.pt]
title = "Documentação para RustDesk"
weight = 2
languageName = "Português"
landingPageName = "<i class='fas fa-home'></i> Pagina inicial"

[Languages.it]
title = "Documentazione per RustDesk"
weight = 2
languageName = "Italiano"
landingPageName = "<i class='fas fa-home'></i> Pagina iniziale"

[Languages.de]
title = "Dokumentation für RustDesk"
weight = 2
languageName = "Deutsch"
landingPageName = "<i class='fas fa-home'></i> Startseite"

[Languages.ja]
title = "RustDeskのドキュメント"
weight = 2
languageName = "日本語"
landingPageName = "<i class='fas fa-home'></i> ホームページ"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
url = "https://github.com/rustdesk/rustdesk"
weight = 10

[Languages.zh-cn]
title = "RustDesk文档"
weight = 3
languageName = "简体中文"
landingPageName = "<i class='fas fa-home'></i> 首页"

[Languages.zh-tw]
title = "RustDesk文檔"
weight = 3
languageName = "繁體中文"
landingPageName = "<i class='fas fa-home'></i> 首頁"

[[Languages.zh.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub 仓库"
identifier = "ds"
url = "https://github.com/rustdesk/rustdesk"
weight = 10
